---
- name: Update webserver and Nfs server
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: Uninstall wireshark
      yum:
        name: wireshark
        state: removed

- name: Update LB-server and DB-server
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: uninstall wireshark
      apt:
        name: wireshark
        state: absent
        autoremove: yes
        purge: yes
        autoclean: yes
