---
- name: Create sample text files on RHEL servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: Creating the directory
      file:
        path: /home/ec2-user/Text-files
        state: directory

    - name: Creating the text file
      file:
        path: /home/ec2-user/Text-files/Testing.txt
        state: touch

- name: Create text files on ubuntu servers
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Creating the directory
      file:
        path: /home/ubuntu/text-files
        state: directory
    - name: creating the text files
      file:
        path: /home/ubuntu/text-files/testing.txt
        state: touch
